### ISSUE TITLE
Error while loading a feather file.

### ISSUE THREAD

**Issue by burhanusman** [mxbi/mlcrate#3]
`comb=mlc.load("comb_all_features1.feather")
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-d8314f431993> in <module>()
----> 1 comb=mlc.load("comb_all_features1.feather")

~/anaconda3/lib/python3.6/site-packages/mlcrate/__init__.py in load(filename)
     33         fp = open(filename, 'rb')
     34 
---> 35     return pickle.load(fp)
     36 
     37 class LinewiseCSVWriter:

ValueError: could not convert string to float: EA1`

**Comment by mxbi** [comment]
Hi @burhanusman, where did you install mlcrate from? feather support is currently only available if you install from git (`python setup.py install`), although it will go out in pip in mlcrate 0.2.0 in the coming days.
